{% set name = "mu_repo" %}
{% set version = "1.5.0" %}
{% set hash_type = "sha256" %}
{% set hash = "f6be0e3a12e5ac7f34d0715eceb929e0076150ed49e5ecb8c506e3d713a7b6f4" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - mu = mu_repo:main_entry_point
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mu_repo

  commands:
    - mu --help

about:
  home: http://fabioz.github.io/mu-repo
  license: GPL3
  summary: 'Tool to work with multiple git repositories'
  license_family: GPL

extra:
  recipe-maintainers:
    - fabioz
    - nicoddemus
