{% set name = "mu_repo" %}
{% set version = "1.8.2" %}
{% set hash = "1394e8fa05eb23efb5b1cf54660470aba6f443a35719082595d8a8b9d39b3592" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - mu = mu_repo:main_entry_point
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

test:
  imports:
    - mu_repo

  commands:
    - mu --help

about:
  home: http://fabioz.github.io/mu-repo
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tool to work with multiple git repositories  

extra:
  recipe-maintainers:
    - fabioz
    - nicoddemus
