{% set name = "mu_repo" %}
{% set version = "1.8.0" %}
{% set hash_type = "sha256" %}
{% set hash = "80c753b33d60f77184910c8a7b7c8b8fcdc821f3337cbf905a3baf62c1fe1f9a" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - mu = mu_repo:main_entry_point
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mu_repo

  commands:
    - mu --help

about:
  home: http://fabioz.github.io/mu-repo
  license: GPL3
  summary: 'Tool to work with multiple git repositories'
  license_family: GPL

extra:
  recipe-maintainers:
    - fabioz
    - nicoddemus
