travis:
  secure:
    BINSTAR_TOKEN: BOz7LaoFivhKbHndF85xkieFFxOh5OXkWmsvOpxHF9z8wGNmWG7X+ckTBlKGb5Np0XWe9cWQ0E3LNMZjxEPrD33Y3dQfgxjVZz4RwDJbh1lfhV1viKsRKmC7jswnhOi2yF+4+51kFlImt2heg62mWzGygR7J0P2Nv4meiIOhcAqgQuCO35x4f8Cepzg65bB7JWk1Iyxd2DUlIo3deNlHcAcAwewZfwFjMT6twvwduhCm2zowAzuPif/IfCcVCemf3g1MK0QkmwjyENoLpZENuwrMRYq+6fYDtKuoTUXIsHI9AFN+vQY2nrrzjeHn5CzKUKGF4zUlO3+2wvmyufHyETxJk54bB/mOOTvZSgczk2r34GPVDwOuJxMD3tfsxF8+Ht03gT+hXBlWmijIHfhr8jXmaKorrNe1ShBf3QRtDgZ1FBR0ZSfqJLhkCZ8ptVTyQNW6Uv7+53uJtd9tjbeu5I5eOvBGsIOh93EPrnGspWBU9iVHVo0snhYd/VLw8i/RZ7GwNJAvIpB+nHzF7R/6GHIMFs1bthHEWAwAnNlrj7/5JQothmnlHh8UhYcsvxS0dchMDHfoc2lE2IrBPoDASuTOsrxCgt1Jh9IygOCqTblm2qV0YDvad7WktOriwqMon8U8WcN828UUaUB3Do0G/+fZ7kTO33i5IoW4TAWBN5c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
