travis:
  secure:
    BINSTAR_TOKEN: LvbMBIqEj5YUWoR0o+cqufitC8ZS6BmxEOU2d4BmKATzags6EDzJ0jeZaf6UQxv3JXBplGvZ+KCYwgI68JfQ84DDdTEmW08CO1KoUWVGKEFuV2da4cB86aTPCzEj00xFIH7mhJy667w51SuUlHAWnkAtqtG/A9SUQz3/LeT5HeF5XJJNHf0A6Zt0BDXghUvwAFTvRpIv+2Bbb2EIvFIMRA7KfzYrQ7F85/B7ZKTQENCPQM54l27/sUYZGHEaYW1WiSQ+TeWZXnzygeO47fElCleQp4rMEHiYgntAlDEEuTr0XkZnv5ktKl+n5W0MxjV0/LNRbmZJtjZ2DuwsP2vhUKdfpMhZ4Ex2AWIT3zkpN2yKt7ECdBRANuAYJiU5cW1bohmV6ORA4aaTcHuGiO2SF3j84Itqv7fPimZB2pOewTVPvWmo7C6ll4B4FdxaJmvKlshRA2QGLseCcJec8lx4csrwuD7iU9ad6w/PZX3KhCjhXJ2yyud59qVQTd2V9hWTp20OKJt5xxnOuEZ3Yf1WQNFAUnH7BwT2Zxb/BbggX0HFZ9eJ2C1i0aNA0FJTfFBigzQA/yDkcTsh2x7vCspJ19ChJv60R3Bd7JFi2U4LIFTvR2s217N5Vc9iX8vkDP+jXLJyMEaP8YoLCRr6L8wFdyz5lG1WiCx/bfvVh0QdcoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
